services:
  - type: web
    name: getknowbie-strapi
    env: node
    buildCommand: ./build.sh
    startCommand: ./start.sh
    healthCheckPath: /_health
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_CLIENT
        value: postgres
      - key: DATABASE_URL
        fromDatabase:
          name: getknowbie-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: API_TOKEN_SALT
        generateValue: true
      - key: TRANSFER_TOKEN_SALT
        generateValue: true
      - key: APP_KEYS
        value: "key1,key2,key3,key4"
      - key: RENDER_EXTERNAL_URL
        fromService:
          name: getknowbie-strapi
          type: web
          property: url

databases:
  - name: getknowbie-db
    plan: free
